### PR TITLE
debian/changelog: Prepare for NMU

### PR DESCRIPTION
**Pull request by nicoonoclaste**
Follow-up on #1, fix the Debian changelog in a way that is suitable for a NMU.

### CODE REVIEW

**Comment by a-dma** [comment]
Thanks!

**Comment by LocutusOfBorg** [comment]
Hi @a-dma do you need a sponsor? please let me know
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826060

**Comment by a-dma** [comment]
Hey,

first off thanks for the offering. I'm not sure I understand what kind of sponsorship you're offering. Is it for the this specific NMU or for me/us to become DM?

I know that lately we've been really bad at keeping the packages in Debian up to date, we basically don't have upload capabilities at the moment. @klali and I have started the procedure to become DM which should hopefully fix the problem, but all help is welcome.

**Comment by LocutusOfBorg** [comment]
Hi, I can help in sponsoring stuff if needed, and with some time to let you become a DM (I need to first trust your work).

So, please give me a dsc file to sponsor, and I'll have a look.
Uploading on mentors is fine

**Comment by nicoonoclaste** [comment]
@LocutusOfBorg I already filed a RFS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826060

**Comment by LocutusOfBorg** [comment]
yes, I'm here _because_ of that RFS :)

I did some tweaks, and sponsored on deferred/2
https://github.com/Yubico/libu2f-server-dpkg/pull/3
this is what I uploaded (you can't delete changelog entries once they entered Debian unstable.

**Comment by nicoonoclaste** [comment]
@LocutusOfBorg Thanks, didn't notice the second PR.

**Pull request merged**
